// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.versions = [
            kotlin             : "1.4.32",
            coroutines         : "1.4.2",
            corectx            : "1.3.2",
            navigation         : "2.3.4",
            activity_ktx       : "1.2.2",
            fragment_ktx       : "1.3.2",
            lifecyclectx       : "2.3.1",
            appcompat          : "1.2.0",
            material           : "1.3.0",
            constraintlayout   : "2.0.4",
            retrofit2          : "2.9.0",
            dagger_hilt        : "2.33-beta",
            hilt               : "1.0.0-beta01",
            logging_interceptor: "4.9.0",
            room               : "2.2.6",
            maps               : "17.0.0",
            location           : "18.0.0",
            input_mask         : "6.0.0"
    ]
    ext.retrofit2 = [
            retrofit     : "com.squareup.retrofit2:retrofit:$versions.retrofit2",
            convertergson: "com.squareup.retrofit2:converter-gson:$versions.retrofit2"
    ]
    ext.navigation = [
            navigationfragmentktx: "androidx.navigation:navigation-fragment-ktx:$versions.navigation",
            navigationuiktx      : "androidx.navigation:navigation-ui-ktx:$versions.navigation",
            safe_args_plugin     : "androidx.navigation:navigation-safe-args-gradle-plugin:$versions.navigation"

    ]
    ext.dagger_hilt = [
            android_gradle_plugin: "com.google.dagger:hilt-android-gradle-plugin:$versions.dagger_hilt",
            android              : "com.google.dagger:hilt-android:$versions.dagger_hilt",
            android_compiler     : "com.google.dagger:hilt-android-compiler:$versions.dagger_hilt"
    ]
    ext.jetpack_hilt = [
            //TODO подставить сюда обычную версию, когда номера библиотек синхронизируют
            viewmodel          : "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha03",
            navigation_fragment: "androidx.hilt:hilt-navigation-fragment:$versions.hilt",
            compiler           : "androidx.hilt:hilt-compiler:$versions.hilt"
    ]
    ext.room = [
            runtime : "androidx.room:room-runtime:$versions.room",
            compiler: "androidx.room:room-compiler:$versions.room",
            ktx     : "androidx.room:room-ktx:$versions.room"
    ]
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
        classpath dagger_hilt.android_gradle_plugin
        classpath navigation.safe_args_plugin

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}