plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'androidx.navigation.safeargs.kotlin'
    id 'kotlin-parcelize'
    id 'com.google.gms.google-services'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.lydone.okna_service_android_app"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    packagingOptions {
        exclude "DebugProbesKt.bin"
    }
}

dependencies {

    implementation "androidx.core:core-ktx:$versions.corectx"
    implementation "androidx.activity:activity-ktx:$versions.activity_ktx"
    implementation "androidx.fragment:fragment-ktx:$versions.fragment_ktx"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$versions.lifecyclectx"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$versions.lifecyclectx"
    implementation "androidx.appcompat:appcompat:$versions.appcompat"
    implementation "com.google.android.material:material:$versions.material"
    implementation "androidx.constraintlayout:constraintlayout:$versions.constraintlayout"
    implementation retrofit2.retrofit
    implementation retrofit2.convertergson
    implementation "com.squareup.okhttp3:logging-interceptor:$versions.logging_interceptor"
    implementation navigation.navigationfragmentktx
    implementation navigation.navigationuiktx
    implementation dagger_hilt.android
    kapt dagger_hilt.android_compiler
    implementation jetpack_hilt.viewmodel
    implementation jetpack_hilt.navigation_fragment
    kapt jetpack_hilt.compiler
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$versions.coroutines"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$versions.coroutines"
    implementation room.runtime
    kapt room.compiler
    implementation room.ktx
    implementation gms.maps
    implementation gms.location
    implementation "com.redmadrobot:input-mask-android:$versions.input_mask"
    implementation platform(firebase.bom)
    implementation firebase.analytics
    implementation firebase.messaging
    implementation "com.google.ar:core:$versions.arcore"
    implementation "com.google.ar.sceneform.ux:sceneform-ux:$versions.sceneform"

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}